import { initializeApp } from "https://www.gstatic.com/firebasejs/12.19.0/firebase-app.js";
import { getFirestore, collection, doc, addDoc, setDoc, onSnapshot, getDoc, updateDoc } from "https://www.gstatic.com/firebasejs/12.19.0/firebase-firestore.js";
// Firebase configuration structure matching your console project targets
const firebaseConfig = {
    apiKey: "AIzaSyDrWo7Fz0I5C_8KIAlp1PfxnCmZ4nuRvQc",
    authDomain: "://firebaseapp.com",
    projectId: "webrtc-signaling-9316c",
    storageBucket: "webrtc-signaling-9316c.firebasestorage.app",
    messagingSenderId: "856316427805",
    appId: "1:856316427805:web:2b45fc786b9f9c33dd50f4",
    measurementId: "G-W7Z0PZJGDL"
};

// Initialize infrastructure
const app = initializeApp(firebaseConfig);
const db = getFirestore(app);

// Public STUN server configuration for local network gathering iterations
const rtcConfig = {
    iceServers: [{'urls': 'stun:stun.l.google.com:19302'}] 
};

let pc = new RTCPeerConnection(rtcConfig);
let roomId = null;
let activeDataChannel = null; // Tracks whichever channel is ready to transmit data

const statusDiv = document.getElementById('status');
const roomIdDisplay = document.getElementById('roomIdDisplay');
const chatBox = document.getElementById('chatBox');
const chatInput = document.getElementById('chatInput');
const sendBtn = document.getElementById('sendBtn');

// Helper tool to render message packets straight onto the UI viewport
function appendToChat(message, type) {
    const msgElement = document.createElement('div');
    msgElement.classList.add('msg', type === 'local' ? 'local-msg' : 'remote-msg');
    msgElement.innerText = type === 'local' ? `You: ${message}` : `Peer: ${message}`;
    chatBox.appendChild(msgElement);
    chatBox.scrollTop = chatBox.scrollHeight; // Auto-scroll downward
}

// Function that handles the opening state events of the Data Channel lanes
function setupDataChannelListeners(channel) {
    activeDataChannel = channel;

    channel.onopen = () => {
        console.log("--> Data Channel path is now completely OPEN.");
        chatInput.disabled = false;
        sendBtn.disabled = false;
        statusDiv.innerText = "Status: DataChannel Connected! Type below.";
        statusDiv.style.color = "#2ecc71";
    };

    channel.onclose = () => {
        console.log("--> Data Channel path has been CLOSED.");
        chatInput.disabled = true;
        sendBtn.disabled = true;
        statusDiv.innerText = "Status: DataChannel Closed.";
        statusDiv.style.color = "#d63031";
    };

    channel.onmessage = (event) => {
        console.log(`[DATA CHANNEL INBOUND]: ${event.data}`);
        appendToChat(event.data, 'remote');
    };
}

// =================================================================
// 🛠️ HOST TRANSCEIVER ENGINE INITIALIZATION (Caller Path Setup)
// =================================================================
// The Caller explicitly creates the local outbox pipe
let callerDataChannel = pc.createDataChannel("chat-channel");
setupDataChannelListeners(callerDataChannel);

pc.onconnectionstatechange = () => {
    console.log(`[PEER CONNECTION STATE CHANGE]: ${pc.connectionState}`);
    statusDiv.innerText = `Status: Connection is ${pc.connectionState.toUpperCase()}`;
    if (pc.connectionState === "connected") statusDiv.style.color = "#2ecc71";
};

pc.onicegatheringstatechange = () => {
    console.log(`[ICE GATHERING STATE CHANGE]: ${pc.iceGatheringState}`);
};

// =================================================================
// 🛠️ REMOTE TRANSCEIVER ENGINE INITIALIZATION (Callee Path Setup)
// =================================================================
// The Callee listens for the remote inbox pipe generated by the host
pc.ondatachannel = (event) => {
    console.log("--> Callee detected a remote inbound data channel configuration.");
    setupDataChannelListeners(event.channel);
};

// ==========================================
// UI ACTION HOOKS: Send Message Action
// ==========================================
sendBtn.addEventListener('click', sendMessageProcessing);
chatInput.addEventListener('keypress', (e) => { if (e.key === 'Enter') sendMessageProcessing(); });

function sendMessageProcessing() {
    const text = chatInput.value.trim();
    if (!text || !activeDataChannel || activeDataChannel.readyState !== "open") return;

    // Send the raw text parameter directly over the P2P connection lane
    activeDataChannel.send(text);
    
    // Log it locally in our own chat UI box container
    appendToChat(text, 'local');
    
    chatInput.value = ""; // Flush buffer box
}

// ==========================================
// CALLER BUTTON ACTION
// ==========================================
document.getElementById('createBtn').addEventListener('click', async () => {
    statusDiv.innerText = "Status: Generating Local Offer...";
    
    // Gather caller network addresses and write to Firebase instantly
    pc.onicecandidate = async (event) => {
        if (event.candidate && roomId) {
            console.log(`[CALLER ICE GATHERED]:`, event.candidate.candidate);
            const candRef = doc(collection(db, 'rooms', roomId, 'callerCandidates'));
            await setDoc(candRef, event.candidate.toJSON());
        }
    };

    const offerDescription = await pc.createOffer();
    await pc.setLocalDescription(offerDescription);

    const offer = {
        sdp: offerDescription.sdp,
        type: offerDescription.type,
    };

    console.log("--- CALLER SDP OFFER CREATED ---");
    console.log(offer.sdp);

    const roomRef = await addDoc(collection(db, 'rooms'), { offer });
    roomId = roomRef.id;
    roomIdDisplay.innerText = roomId;
    statusDiv.innerText = "Status: Room open. Awaiting remote peer answer map...";

    // Start listening for callee candidates IMMEDIATELY upon room validation
    onSnapshot(collection(db, 'rooms', roomId, 'calleeCandidates'), (snapshot) => {
        snapshot.docChanges().forEach(async (change) => {
            if (change.type === 'added') {
                const data = change.doc.data();
                console.log("[CALLER ADDING REMOTE ICE CANDIDATE]:", data.candidate);
                try {
                    await pc.addIceCandidate(new RTCIceCandidate(data));
                } catch (e) {
                    console.error("Error adding remote candidate to caller:", e);
                }
            }
        });
    });

    onSnapshot(roomRef, async (snapshot) => {
        const data = snapshot.data();
        if (!pc.currentRemoteDescription && data?.answer) {
            console.log("--- RECEIVED CALLEE SDP ANSWER FROM FIRESTORE ---");
            console.log(data.answer.sdp);
            const rtcAnswerDescription = new RTCSessionDescription(data.answer);
            await pc.setRemoteDescription(rtcAnswerDescription);
        }
    });
});

// ==========================================
// CALLEE BUTTON ACTION
// ==========================================
document.getElementById('joinBtn').addEventListener('click', async () => {
    roomId = document.getElementById('roomInput').value.trim();
    if (!roomId) return alert("Please enter a valid Room ID first!");

    statusDiv.innerText = `Status: Fetching Room ${roomId}...`;
    const roomRef = doc(db, 'rooms', roomId);
    const roomSnapshot = await getDoc(roomRef);

    if (!roomSnapshot.exists()) {
        statusDiv.innerText = "Status: Room code not found in Cloud database.";
        return;
    }

    // Gather callee network addresses and write to Firebase instantly
    pc.onicecandidate = async (event) => {
        if (event.candidate) {
            console.log(`[CALLEE ICE GATHERED]:`, event.candidate.candidate);
            const candRef = doc(collection(db, 'rooms', roomId, 'calleeCandidates'));
            await setDoc(candRef, event.candidate.toJSON());
        }
    };

    const roomData = roomSnapshot.data();
    const offerDescription = roomData.offer;
    
    console.log("--- CALLEE FETCHED HOST SDP OFFER ---");
    console.log(offerDescription.sdp);
    
    // 1. Set the Remote Description FIRST. This resolves the async race condition.
    await pc.setRemoteDescription(new RTCSessionDescription(offerDescription));

    // 2. NOW that the remote offer is safely configured, sync incoming Caller candidates
    onSnapshot(collection(db, 'rooms', roomId, 'callerCandidates'), (snapshot) => {
        snapshot.docChanges().forEach(async (change) => {
            if (change.type === 'added') {
                const data = change.doc.data();
                console.log("[CALLEE ADDING REMOTE ICE CANDIDATE]:", data.candidate);
                try {
                    await pc.addIceCandidate(new RTCIceCandidate(data));
                } catch (e) {
                    console.error("Error adding remote candidate to callee:", e);
                }
            }
        });
    });

    // 3. Formulate the local response answer profiles 
    const answerDescription = await pc.createAnswer();
    await pc.setLocalDescription(answerDescription);

    const answer = {
        type: answerDescription.type,
        sdp: answerDescription.sdp,
    };

    console.log("--- CALLEE SDP ANSWER GENERATED ---");
    console.log(answer.sdp);

    // 4. Update the cloud document to send the answer back to the caller
    await updateDoc(roomRef, { answer });
    statusDiv.innerText = "Status: Dispatched answer mapping. Building P2P path...";
});

